site_name: SECP256k2
site_description: 'Documentation for SECP256k2'
site_author: 'Pymmdrza@gmail.com'
repo_url: 'https://github.com/secp256k2/secp256k2'
nav:
    - Home: 'index.md'
    - document: 'https://github.com/secp256k2/secp256k2'
    - Bug Tracking: 'https://github.com/secp256k2/secp256k2/issues'
    - Pull Requests: 'https://github.com/secp256k2/secp256k2/pulls'
    - Source: 'https://github.com/secp256k2/secp256k2'
    - CryptoFuzz: 'https://pymmdrza.github.io/cryptoFuzz/doc/'
    - Blockthon: 'https://blockthon.github.io/Blockthon/'

theme:
    name: 'material'
    features:
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.tracking
        - navigation.expand
        - navigation.path
        - navigation.instant.prefetch
        - navigation.instant
        - toc.follow
        - search.suggest
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

docs_dir: './docs'
plugins:
  - search

